version: '3.9'
services:
  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=kaf
      - POSTGRES_PASSWORD=kaf123
    volumes:
      - ./docker-dev:/docker-entrypoint-initdb.d
      - db_data:/data/postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kaf']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
volumes:
  db_data:
